### ISSUE TITLE
Multiple file support

### ISSUE THREAD

**Issue by Saim-Khan1** [PseudocodeEditor/Codemirror-6-editor#10]
Add support for multiple files in the editor, having a single instance of the editor and switching the content in it:
```js
const update = editor.state.update({changes: {from: 0, to: editor.state.doc.length, insert: content}})
editor.update([update])
```

**Comment by Saim-Khan1** [comment]
Including functionality to create a new file, upload files/folder, and download individual files or the entire project as a ZIP.

**Comment by hugomarf** [comment]
All completed - Project downloaded as a .pscp file not a zip
