### ISSUE TITLE
Files not working

### ISSUE THREAD

**Issue by hugomarf** [PseudocodeEditor/Codemirror-6-editor#13]
The load file and save file buttons no longer work.

### Expected Behaviour
When the load and save button are pressed it does exactly that

### Actual Behaviour
When the load file button is pressed the men to choose the file comes up however when the file is selected nothing happens.

When the save file button is pressed nothing happens.

**Comment by Coding-Cactus** [comment]
Files don't exist

**Comment by hugomarf** [comment]
@Coding-Cactus  see updated description above. I was writing it when you added this.

**Comment by Saim-Khan1** [comment]
Sorry yep, that was me lol
I broke that temporarily to get the editor working on the new site again (the error where it was looking for elements that didn't exist)
Will fix shortly

**Comment by Saim-Khan1** [comment]
All fixed now :)
