### ISSUE TITLE
Accessibility Mode

### ISSUE THREAD

**Issue by hugomarf** [PseudocodeEditor/Codemirror-6-editor#4]
### Features to include

- High Contrast theme

- OpenDyslexic / Dyslexic Friendly font

- Ability to adjust font size and spacing

**Comment by hugomarf** [comment]
Currently looking into best fonts to use for accessible code:
- Open Dyslexic is the leading contender

Syntax High lighting with a high contrast theme most likely using Xcode colours as they will have done research on the science behind it. Colour codes and examples can be found below:

```
Background: #18171B
Selection: #343C4B
Cursor: #FFFFFF
Current Line: #23252B
Invisibles: #424D5B
Plain Text: #FFFFFF
Comments: #7CB554
Documentation Markup: #7CB554
Documentation Markup Keywords: #ACF07B
Marks: #ACF07B
Strings: #FC7467
Characters: #D0BC56
Numbers: #D0BC56
Keywords: #FC6BAA
Preprocessor Statements: #FD8F3F
URLs: #739AFF
Attributes: #E1A779
Type Declarations: #5DD8FF
Other Declarations: #42B8E0
Project Class Names: #A4FBE6
Project Function and Method Names: #72BFAE
Project Constants: #72BFAE
Project Type Names: #A4FBE6
Project Instance Variables and Globals: #72BFAE
Project Preprocessor Macros: #FD8F3F
Other Class Names: #DEC1FF
Other Function and Method Names: #C08AFF
Other Constants: #C08AFF
Other Type Names: #DEC1FF
Other Instance Variables and Globals: #C08AFF
Other Preprocessor Macros: #FD8F3F
Heading: #AA0D91
```
![Example of High Contrast Theme](https://user-images.githubusercontent.com/58790608/160788240-ea81516e-7f68-4f60-8421-900b90fce723.png)
@Saim-Khan1 Hope this saves a bunch of time

**Comment by Coding-Cactus** [comment]
Are those the colours for the Xcode high contrast theme or just the general theme?

**Comment by Saim-Khan1** [comment]
> Are those the colours for the Xcode high contrast theme or just the general theme?

They're the Xcode High Contrast theme colours, I think they look pretty good and as @hugomarf said they will have done their research into it so I think it makes sense

**Comment by hugomarf** [comment]
> > Are those the colours for the Xcode high contrast theme or just the general theme?
> 
> They're the Xcode High Contrast theme colours, I think they look pretty good and as @hugomarf said they will have done their research into it so I think it makes sense

I have actually used this them and I do like it because it's not as aggressive as other high contrast themes but still achieves the goal of increasing readability.

**Comment by Saim-Khan1** [comment]
The high contrast theme has now been implemented. In terms of the
> * Ability to adjust font size and spacing
I'm going to move that over to issue #3 because it's more to do with reconfiguring the editor's state and giving the user more options, just as allowing them to change the theme is as well.
