### ISSUE TITLE
No unindent after ELSE statement

### ISSUE THREAD

**Issue by hugomarf** [PseudocodeEditor/Codemirror-6-editor#8]
**Describe the bug**
When typing ENDIF after an ELSE statement the code does not auto-unindent

**To Reproduce**
1. Type in the code:. 
```
	IF ifFull() = TRUE THEN
		RETURN FALSE
	ELSE
		data[free] <- dataToAdd
		tempPointer <- pointers[free]
		pointers[free] <- head
		head <- free
		free <- tempPointer
		pointers[tail] <- free
		RETURN TRUE
		ENDIF
```
2. Hit enter after ENDIF

**Expected behavior**
The editor does not unindent after enter has been pressed

**Screenshots**
![CleanShot 2022-03-30 at 9 42 55](https://user-images.githubusercontent.com/58790608/160927395-0f6ed178-ba55-427d-8337-eba3df8cd36d.png)

**Comment by hugomarf** [comment]
@Coding-Cactus any idea what's going on?

**Comment by Coding-Cactus** [comment]
The auto indent check occurs once you type the word, rather than when you add whitespace after it

**Comment by Saim-Khan1** [comment]
Yep, works fine for me
![image](https://user-images.githubusercontent.com/70058899/160928944-111975cd-5561-4c31-a7fe-f5437e075f7a.jpeg)

**Comment by hugomarf** [comment]
Ah yes ask good!
